### PR TITLE
👌 IMPROVE: align text from end to center

### PR DESCRIPTION
**Pull request by saqibameen**
Changes the button text from end to center in the message. 

PR changes GIF

### CODE REVIEW

**Comment by idoshamun** [comment]
Thanks for the contribution and the awesome GIF :grin:  If I recall correctly @tsahimatsliah did it on purpose... @tsahimatsliah what do you think?

**Comment by saqibameen** [comment]
Oh, I didn't know about that. Feel free to close the PR in that case. :)

**Comment by idoshamun** [comment]
The thing is that if you felt is not right then maybe others feel the same way. This is why I'm considering accepting this PR but I need @tsahimatsliah approval on this one.

**Comment by tsahimatsliah** [comment]
@saqibameen Thanks for the contribution and help us to make daily better, I totally agree with you!
Let's make the change :)

**Pull request merged**
