### PR TITLE
Fix banners above header and rank-btn 

### PR DESCRIPTION
**Pull request by zvikarp**
related to https://github.com/dailydotdev/daily/issues/225

### CODE REVIEW

**Comment by idoshamun** [comment]
Hey @zvikarp,

I tested this PR and the order of the DND banner and the promotional banner is great but they're all positioned fixed.
This causes some buttons in the header to be inaccessible. I believe it's better to just position them as part of the general layout so everything else will be pushed down accordingly.

Lmk what you think 🙏

image

**Comment by zvikarp** [comment]
Yeah, you have a good point, The banner was fixed before, so I kept it. I'll update this PR

**Comment by zvikarp** [comment]
@idoshamun it seems like the rank button is in the home component, not the header. This means it would be hard (and a hacky workaround) to get its position based on if the DND or banner is open. I suggest moving it to the header component therefor its position would be relative to it.

What do you think?

**Comment by idoshamun** [comment]
Sounds good. Let's try it out :)

**Comment by zvikarp** [comment]
lol sorry for the failed builds. 

The banners don't overlap the header anymore, I believe I did all the needed changes but don't know all the edge-cases so could be I missed something.

One thing I noticed, When the banner or DND is open, and you click on the rank button, the modal icon doesn't appear on top of the rank button but it is a modal and not a tooltip so I think it is fine.

**Comment by idoshamun** [comment]
Doing some manual QA, I found misbehavior with the positioning of the banner.
Look at the screenshot below, there's a gap between the promotional banner and the top of the document.
image

**Comment by zvikarp** [comment]
@idoshamun sorry about that. I hard-coded the banner in because I don't know how to create one 😆, I guess I was missing something, fixed it.

How do you add the banner for testing?

**Comment by idoshamun** [comment]
You can add a banner object to the table banner table. Make sure to disable cache in the extension.
Have a look
image

**Review by idoshamun — APPROVED** [review]
Now it looks great!
Thank you so much for bearing with me on this 🏅

**Pull request merged**
